name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Remove .npmrc to avoid using private registries
        run: rm .npmrc
      - name: Install TFX
        run: npm install -g tfx-cli
      - run: |
          npm install
      - run: |
          npm run all
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: vsix
          path: ms-wpd-winappcli.windows-app-development-cli-setup-task-*.vsix

  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./
      - run: winapp --version